### ISSUE TITLE
Add more snooze options per notification

### ISSUE THREAD

**Issue by Allineer** [jonasbleyl/Recurrence#10]
About notifications... I think, it must to be more obtrusive — they must be periodically repeated over and over and over again without any further actions from the user. They should force the user to pay attention to the reminder and then make it possible to snooze for a while.
And it is very convenient to be able to choose the time at which you can to snooze each specific reminder. For example: "Snooze for a X minutes/hours/days".

Now, I'm using [this](https://play.google.com/store/apps/details?id=com.bzzzapp&hl=en) app. It has an aversome functions, but poor UI/UX.

Thanks.

**Comment by jonasbleyl** [comment]
Regarding the first suggestion: If the objective is to make the notification impossible to miss, then I think it would be more effective by having the ability to set a ringtone, or a custom sound, as the notification sound. 

The second suggestion is something I will definitely add though.

**Comment by Allineer** [comment]
> would be more effective by having the ability to set a ringtone, or a custom sound

we have the ability to set system notification sound. I still think, that we need just repeat it over and over.

**Comment by dreaming-augustin** [comment]
I don't know why this issue was closed.
I still would like to have more settings to be per notification.
Having presets would allow us to differentiate between obtrusive notifications and non-obtrusive ones.
I discuss all this here:
https://github.com/jonasbleyl/Recurrence/issues/24
