### ISSUE TITLE
Edit notification button visibility

### ISSUE THREAD

**Issue by Allineer** [jonasbleyl/Recurrence#11]
How about change the Edit notification menu item to the button beside of the Delete button on the action bar?

I mean... View Notification activity has no menu on the action bar, but have 2 buttons after this changes.
And I think, it necessary to add an "Delete" item to the context menu on this activity.

Thanks.

PS: sorry for my English

**Comment by jonasbleyl** [comment]
Not sure what you mean. Could you elaborate?
You mean moving the edit button in the ViewActivity next to the delete button so that it isn't in the overflow menu?

**Comment by Allineer** [comment]
Yes, it is.
