### ISSUE TITLE
Set the minutes: step

### ISSUE THREAD

**Issue by Allineer** [jonasbleyl/Recurrence#14]
When we selectiong time for a notification, we need to scroll from 00 to 59 minutes every time.
Perhaps it makes sense to shorten the list, using the five-minute intervals:

00
05
10
...
50
55

?

**Comment by jonasbleyl** [comment]
That form of the time picker is only used on older versions of android. I'm pretty sure the number can be typed in using the keyboard anyway. 

Please stop spamming my issue tracker.
