### ISSUE TITLE
[FR] Remind of notifications produced by other apps

### ISSUE THREAD

**Issue by ildar** [jonasbleyl/Recurrence#15]
When I read the description of the app I thought that the app I waited for a long time arrived at last! Bad luck :(
What do you think about reminding about notifications made by other apps, e.g. Gmail? I.e. if the user missed the new mail notification, the app could (recurrently) remind about those.
I know that this requires "Accessibility app confirmation" from the user to read notifications, but I hope this isn't too complicated to implement. What do you think?

**Comment by jonasbleyl** [comment]
Sorry, this is not what the app is meant for. Adding that would completely change the functionality of the app!

This is the app you're looking for: https://play.google.com/store/apps/details?id=com.ryosoftware.notificationsmanager

**Comment by ildar** [comment]
Yes, it looks suitable. But it is not opensource, I suspect.
Thanks for dropping the link.
