### ISSUE TITLE
Feature requests: recurring notification reminder 5 min,,10 min

### ISSUE THREAD

**Issue by nutpantz** [jonasbleyl/Recurrence#18]
I have just started using this excellent app
But with most things Android there is no recurring reminder sound/vibrating if you miss the first occurrence. It would be helpful if it was possible to set a notification to reminded you every 1,5,10,15, or 30 minutes or until removed or snoozed.

It would also be quite fantastic if it was possible to set a custom notification sound for each individual reminder. So if you had a number of reminders during the day you could tell what they were by the sound and not have to check the device.

Thank you for all your excellent work on this app and putting it on fdroid

**Comment by dreaming-augustin** [comment]
There is already a snooze option in the general settings.
Is that what you're looking for? 
Unfortunately, it's currently a setting for all items or none of them:
https://github.com/jonasbleyl/Recurrence/issues/24

**Comment by wintermutecx** [comment]
There was another app I used years ago that had a persistent ringtone, that was configurable. For example, you have a reminder set to go off at 8pm, but at that exact time you're taking out the garbage and the device is in the house, you missed the initial ringtone.  If the reminder wasn't acknowledged in a period of time, say 5 minutes, it would jingle the ringtone again. That would repeat, say 6 times or what ever was configured. That way, if you missed the initial ring, you would still be reminded again shortly.

**Comment by jonasbleyl** [comment]
Added in the most recent update.
