### ISSUE TITLE
Edit notification: do not launch keyboard

### ISSUE THREAD

**Issue by dreaming-augustin** [jonasbleyl/Recurrence#26]
When I edit a notification, the cursor/focus in on the title field, and my smartphone automatically launch the keyboard application to allow me to edit the title.
However, I find this mostly annoying because most of the time, I do not want to edit the title. I simply want to change the time, or edit something else. It makes such easy tasks less straightforward and wastes time: I have to wait until my phone reacts to the fact that the focus is on a text field, wait for it to launch the keyboard application, then I must dismiss the keyboard by pressing the back button, before I can finally access the setting that I wanted to edit in the first place...

**Comment by dreaming-augustin** [comment]
Thank you!
I'll check this as soon as F-Droid has the update.
:)

**Comment by jonasbleyl** [comment]
No problem!

I only made a few changes this version as I wanted to push the fix ASAP for doze delaying alarms on android Marshmallow. But I did this one since it's a simple change :)
