### ISSUE TITLE
Feature Request: Backup

### ISSUE THREAD

**Issue by sbennett18** [jonasbleyl/Recurrence#27]
Would love to have the ability to backup or even share reminders. Could be a simple text export (e.g. xml, json) or plug in to various services (e.g. Dropbox, Drive).

**Comment by jpotier** [comment]
Yeah, right now I would love this enhancement too : ]
Shame I have to lose it all when changing ROMs

**Comment by jonasbleyl** [comment]
I decided to make this an IAP. It was added in the most recent update.
