### ISSUE TITLE
[Feature Request] Sync with Google calender.

### ISSUE THREAD

**Issue by lovebdsobuj** [jonasbleyl/Recurrence#40]
Synchronize `Recurrence` content with Google calender. I hope It will very good.

**Comment by jonasbleyl** [comment]
Google Calendar already has its own reminders: https://gmail.googleblog.com/2015/12/add-to-dos-to-your-google-calendar.html 
There's not much point in implementing duplicate features.

**Comment by lovebdsobuj** [comment]
Okay,
Can you help me,
I want to add some pre-built/built-in event in Database.

Like...
`db.execSQL("INSERT INTO `

**Comment by jonasbleyl** [comment]
Any reason you can't manually add this in the app itself?

If not then you're better off interacting with the database instead of trying to insert into it using SQL. Less likely for something to go wrong. If you're looking to easily add a lot of events into the database then you could do something like the code below. And just put it in a for loop or something.

```java
Calendar calendar = Calendar.getInstance();
calendar.set(Calendar.SECOND, 0);
calendar.set(Calendar.HOUR_OF_DAY, 19);
calendar.set(Calendar.MINUTE, 15);
calendar.set(Calendar.DAY_OF_MONTH, 14);
calendar.set(Calendar.MONTH, 3); // Months start on 0
calendar.set(Calendar.YEAR, 2016);

DatabaseHelper database = DatabaseHelper.getInstance(this);

Reminder reminder = new Reminder()
        .setId(database.getLastNotificationId() + 1)
        .setTitle("YOUR TITLE")
        .setContent("YOUR CONTENT")
        .setDateAndTime(DateAndTimeUtil.toStringDateAndTime(calendar))
        .setRepeatType(Reminder.DOES_NOT_REPEAT)
        .setForeverState("false")
        .setNumberToShow(1)
        .setNumberShown(0)
        .setIcon("ic_notifications_white_24dp")
        .setColour("#8E8E8E")
        .setInterval(1);

database.addNotification(reminder);
database.close();

Intent alarmIntent = new Intent(this, AlarmReceiver.class);
AlarmUtil.setAlarm(this, alarmIntent, reminder.getId(), calendar);
```

**Comment by lovebdsobuj** [comment]
> And just put it in a for loop or something.

Sir, 
If you don't mind, 
Can you tell me pls, 
Where I put this Which class?

**Comment by jonasbleyl** [comment]
Not really too important where you put it. You could add it to `onCreate` in the `MainActivity`.

Do note however that the Github version and play store version aren't the same. The Github version does not have the ability to back up the database.

What you could do is use the play store version of Recurrence, backup the database, edit the SQLite database by using some desktop tool and then restore it from within the app. Using the backup feature does require the pro version however.
