### ISSUE TITLE
Static the job everydoy

### ISSUE THREAD

**Issue by clccc** [jonasbleyl/Recurrence#41]
I was wondering if you can add the statistical data about job done.  And is it better if modify the  job-deleted
 action as drag to right，so i will not delete it with misoperation. This is my dream app, thank you very much.

**Comment by jonasbleyl** [comment]
> add the statistical data about job done

Is there really a need for this? Seem kind of unnecessary. 

> modify the job-deleted action as drag to right, so i will not delete it with misoperation

I'm not sure what you mean by this. Could you explain this further?
