### ISSUE TITLE
Feature: Tree/outline view or section

### ISSUE THREAD

**Issue by neomodern** [jonasbleyl/recurrence#51]
[Tree view](https://en.m.wikipedia.org/wiki/Tree_view) allows dividing a single list into multiple sections, or this could be done by adding a heading or some other way of dividing up a list.

**Comment by jonasbleyl** [comment]
I'm personally not a fan of the tree view in an app like this. I feel it's overly complex for just separating reminders. Most people will not have many that many active reminders going on for this to really be necessary. Sorry.

**Comment by neomodern** [comment]
Tree view is maybe too much, what I really meant is the ability to ident reminders by one step at least.

In my opinion it otherwise limits a list to about one or two dozen easily scannable items. When I use GTasks for example it only allows 1 indentation level but it makes it far easier to pick out the item I'm looking for going through the list.
