### ISSUE TITLE
Share target

### ISSUE THREAD

**Issue by Ketrel** [jonasbleyl/recurrence#53]
I use this and a similar app (which I'm hoping to finally stop using as with the exception of the two features I mentioned, this is a much more featured app).

The first is being a share target.  It would be quite useful to share things like links, text, etc and be able to share it to Recurrence and have it fill in a notification with the shared data.

The second is a persistent notification so I can't accidentally swipe it away.  That's very useful for reminders. Such as "pick up pet food". that way I actively have to delete it rather than accidentally swipe it away if I'm mass swiping away notifications, or simply just a mistake.

**Comment by jonasbleyl** [comment]
The first request is something I definitely need to add.

Though the persistent notification setting is already an option in the app's settings! 
Overflow menu > Settings > Persistent

**Comment by Ketrel** [comment]
Sorry, I was vague.  I meant on a per-item basis.  I saw the overall setting.

The ones I set to happen daily, those I'd like to swipe away, but the ones I set like "do this before sleeping" I'd like to keep persistent.

**Comment by jonasbleyl** [comment]
I'll close this issue due to the shared-text request since I've now added that. I still have the per-reminder persistent option on my to-do list.
