### ISSUE TITLE
Expose hard coded values

### ISSUE THREAD

**Issue by Primokorn** [jonasbleyl/recurrence#54]
Hi,

Please expose [these hard coded values](https://osine.cozycloud.cc/public/hastebin/GenFhyGc).
Layout folders can't be used with the Cyanogenmod theme engine. Please redirect them to values > colors.xml for instance.

Thanks a lot!

**Comment by jonasbleyl** [comment]
Yeah, this is completely fine to change. Want to send a pull request for this to get this added sooner? 

Feel free to add some colour values since currently several different unrelated views share the same specific colour declaration.

**Comment by Primokorn** [comment]
Give me a few days for the PRs. I'll do it this weekend. Thanks.

**Comment by Primokorn** [comment]
I created 3 PRs to expose some values to colors.xml. Thanks :)

**Comment by jonasbleyl** [comment]
Merged. Thanks for that.
