### ISSUE TITLE
The alarm is sometimes 2 minutes late

### ISSUE THREAD

**Issue by yenitsrm** [jonasbleyl/recurrence#60]
![screenshot_2016-12-14-12-36-18](https://cloud.githubusercontent.com/assets/12757775/21191176/fd5e7a16-c22c-11e6-98dc-b2dff4a56ecc.png)

**Comment by jonasbleyl** [comment]
I'll need some device info to debug this (device model, android version).

**Comment by yenitsrm** [comment]
ok. Reeder P10, android 5.1

**Comment by jonasbleyl** [comment]
There's not much information about that device. Do you know what kind of android skin it is running? Based on the screenshot it looks like MIUI. You might need to disable the power saving for that app to prevent notifications from getting delayed.

Settings -> Additional settings -> Battery -> Manage apps battery usage -> Power saving modes -> Off

Or something like that.

Seeing as though there have been no other reports of delayed notifications it seems to be device specific though.

**Comment by yenitsrm** [comment]
Thank you. I have disabled the Setting --> Standby intelligent power saving  and it worked. But Is there another way to overcome this? Other applications are working properly in standby mode. for example the aCalendar.

**Comment by jonasbleyl** [comment]
I've searched but I haven't found a way to get around this issue. I'm really not sure how some apps work correctly unless they're whitelisted somehow. If I find a way overcome this then I'll implement it.
