### ISSUE TITLE
java.lang.NoSuchFieldError: No static field colorBackgroundFloating 

### ISSUE THREAD

**Issue by ManuBabu** [jonasbleyl/recurrence#65]
Hi @jonasbleyl , I am getting this error, tried changing the dependency versions, still i am getting this error when i click on defaulf color in create remainder activity.  please help 
 java.lang.NoSuchFieldError: No static field colorBackgroundFloating of type I in class Lcom/afollestad/materialdialogs/R$attr; or its superclasses (declaration of 'com.afollestad.materialdialogs.R$attr' appears in /data/app/manu.poketcommerce.com.openofficeuser-1/base.apk)

**Comment by jonasbleyl** [comment]
Did you try and add the core library as well like the dev said in the other issue you commented in? If not then just roll back to a version that works.
