### ISSUE TITLE
Repeat every X hours/days/weeks/months/years

### ISSUE THREAD

**Issue by Allineer** [jonasbleyl/Recurrence#9]
Hello!
Thanks for the aversome app!

Can your add a some features:

- Repeat every hour
- Repeat every X hours/days/weeks/months/years.

By example:
- Remind me about the necessity take medications every 6 hours.
- Remind me to water the homeplants every 5 days.

And I think, we can remove the "Number of times to repeat" - it does not make sense, because reminder can be removed when it is no longer necessary.

I think this will make the Recurrence more flexible and universal.

**Comment by jonasbleyl** [comment]
Yeah these are good suggestions. I'll add them to my to-do list.

I will keep "Number of times to repeat" though as it is useful to some. Users who wish not to use it can always set the notification to repeat forever.

**Comment by Allineer** [comment]
Ok, you are right. Thanks.

**Comment by dreaming-augustin** [comment]
I don't know why this issue was closed, since the feature does not seem to have been implemented.
I don't know how to re-open it.

**Comment by dalb8** [comment]
I'd appreciate this feature myself. I would definitely have some Nightingale song go off each hour. It's the sort of thing that mindfulness teachers recommend.

**Comment by jonasbleyl** [comment]
Added in the most recent update.
